server:
  servlet:
    context-path: /ninja-service
  port: 9091

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/psbportals
    username: root
    password: atumar4031